service:
  name: kubeless-ts
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-kubeless

provider:
  name: kubeless
  runtime: nodejs12

functions:
  hello:
    handler: handler.hello
